In [1]:
import pandas as pd 
import numpy as np 
import os 

# data
path_folder = r"D://NEW PORTFOLIO//olist_all datasets//all_dataset" # folder 
files = [f for f in os.listdir(path_folder) if f.endswith('.csv')] # get all files end in csv
# looping 
for file in files:
    full_path = os.path.join(path_folder, file)
    df = pd.read_csv(full_path, sep=None, engine = 'python', on_bad_lines='skip')

    print(f"loading dataset: {file}")
    print(f"shape(row, column):{df.shape}")

    display(df.head(5))
    print("-"*50)

C:\Users\DYAR NUR WULAN\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\DYAR NUR WULAN\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

loading dataset: olist_customers_dataset.csv
shape(row, column):(99441, 5)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

--------------------------------------------------
loading dataset: olist_geolocation_dataset.csv
shape(row, column):(1000163, 5)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

--------------------------------------------------
loading dataset: olist_orders_dataset.csv
shape(row, column):(99441, 8)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

--------------------------------------------------
loading dataset: olist_order_items_dataset.csv
shape(row, column):(112650, 7)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

--------------------------------------------------
loading dataset: olist_order_payments_dataset.csv
shape(row, column):(103886, 5)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

--------------------------------------------------
loading dataset: olist_order_reviews_dataset.csv
shape(row, column):(99224, 7)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

--------------------------------------------------
loading dataset: olist_products_dataset.csv
shape(row, column):(32951, 9)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

--------------------------------------------------
loading dataset: olist_sellers_dataset.csv
shape(row, column):(3095, 4)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

--------------------------------------------------
loading dataset: product_category_name_translation.csv
shape(row, column):(71, 2)

   ﻿product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

--------------------------------------------------

In [2]:
data = {}
for file in files:
    full_path = os.path.join(path_folder, file)
    table_name = file.replace('.csv','')
    df = pd.read_csv(full_path, sep=None, engine='python', on_bad_lines='skip')
    df.columns = df.columns.str.replace('\ufeff','').str.strip().str.lower()
    data[table_name] = df

In [3]:
for name, df in data.items():
    print(df.dtypes)
    print("-"*40)

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object
----------------------------------------
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object
----------------------------------------
order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object
----------------------------------------
order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object
----------------------------------------
order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object
----------------------------------------
review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object
----------------------------------------
product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object
----------------------------------------
seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object
----------------------------------------
product_category_name            object
product_category_name_english    object
dtype: object
----------------------------------------

In [4]:
for table_name, df in data.items():
    
    obj_cols = df.select_dtypes(include=['object']).columns
    
    df[obj_cols] = df[obj_cols].apply(lambda x: x.astype(str).str.strip())

    num_str_cols = [c for c in df.columns if any(k in c.lower() for k in ['price', 'value'])]
    for col in num_str_cols:
        if df[col].dtype == 'object':
            df[col] = df[col].str.replace('.', '', regex=False).str.replace(',', '.', regex=False)
            df[col] = pd.to_numeric(df[col], errors='coerce')
    
    for col in df.columns:
        time_keywords = ['_at', 'timestamp', 'date', 'delivery']
        if any(key in col.lower() for key in time_keywords):
            df[col] = pd.to_datetime(df[col], errors='coerce')
            
    print(f" all cleaning steps finished for {table_name}")

 all cleaning steps finished for olist_customers_dataset
 all cleaning steps finished for olist_geolocation_dataset
 all cleaning steps finished for olist_orders_dataset
 all cleaning steps finished for olist_order_items_dataset
 all cleaning steps finished for olist_order_payments_dataset
 all cleaning steps finished for olist_order_reviews_dataset
 all cleaning steps finished for olist_products_dataset
 all cleaning steps finished for olist_sellers_dataset
 all cleaning steps finished for product_category_name_translation

In [5]:
for name, df in data.items():
    print(df.dtypes)
    print("-"*40)

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object
----------------------------------------
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object
----------------------------------------
order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object
----------------------------------------
order_id                       object
order_item_id                   int64
product_id                     object
seller_id                      object
shipping_limit_date    datetime64[ns]
price                         float64
freight_value                 float64
dtype: object
----------------------------------------
order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object
----------------------------------------
review_id                          object
order_id                           object
review_score                        int64
review_comment_title               object
review_comment_message             object
review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object
----------------------------------------
product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object
----------------------------------------
seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object
----------------------------------------
product_category_name            object
product_category_name_english    object
dtype: object
----------------------------------------

In [6]:
from sqlalchemy import types

sql_dtype_map = {}
for name, df in data.items():
    column_specs = {}
    for col in df.columns:
        if 'id' in col.lower():
            column_specs[col] = types.VARCHAR(50)
        elif any(key in col.lower() for key in ['city', 'state', 'category', 'name']):
            if 'state' in col.lower():
                column_specs[col] = types.VARCHAR(10)
            else:
                column_specs[col] = types.VARCHAR(100)
    sql_dtype_map[name] = column_specs
print("varchar for id and category done")

varchar for id and category done

In [7]:
print(sql_dtype_map['olist_orders_dataset'])

{'order_id': VARCHAR(length=50), 'customer_id': VARCHAR(length=50)}

In [8]:
for name, df in data.items():
    num_cols = df.select_dtypes(include=['number']).columns
    obj_cols = df.select_dtypes(include=['object']).columns
    data[name][num_cols] = df[num_cols].fillna(0)
    data[name][obj_cols] = df[obj_cols].fillna('Unknown')

In [9]:
print("Checking Missing Values All Tables")
for name, df in data.items():
    total_null = df.isnull().sum().sum() # count all cell 
    # logic for status message
    if total_null == 0:
        status = "CLEAN"
    else:
        status = f"{total_null} NULLS"
    # formatting the output for a neat table look 
    print(f"{name:<40} | {status:<15}")

print("="*60)

Checking Missing Values All Tables
olist_customers_dataset                  | CLEAN
olist_geolocation_dataset                | CLEAN
olist_orders_dataset                     | 4908 NULLS
olist_order_items_dataset                | CLEAN
olist_order_payments_dataset             | CLEAN
olist_order_reviews_dataset              | CLEAN
olist_products_dataset                   | CLEAN
olist_sellers_dataset                    | CLEAN
product_category_name_translation        | CLEAN
============================================================

In [10]:
print(data['olist_orders_dataset'].isnull().sum())

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [11]:
print(data['olist_products_dataset']['product_category_name'].isnull().sum())

0

In [12]:
# translations
products = data['olist_products_dataset'].copy()
translation = data['product_category_name_translation'].copy()

translation.columns = translation.columns.str.replace('\ufeff','').str.strip()
products.columns = products.columns.str.strip()
# merge
try:
    products = pd.merge(products, translation, on='product_category_name', how = 'left')
    # use english
    products['product_category_name'] = products['product_category_name_english'].fillna(products['product_category_name'])
    
    products.drop('product_category_name_english', axis = 1, inplace=True)
    #
    data['olist_products_dataset'] = products
    display(data['olist_products_dataset'].head())
    
except KeyError as e:
    print(f"still keyerrorr: {e}")

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumery,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,art,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,sports_leisure,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,baby,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,housewares,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [13]:
# checking translation 
null_count = data['olist_products_dataset']['product_category_name'].isnull().sum()
if null_count == 0:
    print("All translations were successful")
else:
    print(f"There are null {null_count} missing translations")

All translations were successful

In [14]:
# validation 
final_check = data['olist_products_dataset']['product_category_name'].isnull().sum()
print(f"blank: {final_check}")
if final_check == 0:
    print("data was cleaned")

blank: 0
data was cleaned

In [15]:
# duplicate 
for table_name, df in data.items():
    total_duplicate = df.duplicated().sum()
    print(f"table {table_name}: {total_duplicate}")

table olist_customers_dataset: 0
table olist_geolocation_dataset: 261831
table olist_orders_dataset: 0
table olist_order_items_dataset: 0
table olist_order_payments_dataset: 0
table olist_order_reviews_dataset: 0
table olist_products_dataset: 0
table olist_sellers_dataset: 0
table product_category_name_translation: 0

In [20]:
import pymysql 
from sqlalchemy import create_engine, text

user = "root"
password = "Dyarnw210103*"
host = "localhost"
port = "3306"
database = "olist_db"
engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}")

for table_name, df in data.items():
    clean_name = table_name.replace('olist_','').replace('_dataset','')
    target_dtypes = sql_dtype_map.get(table_name,{})
    try:
        
        df.to_sql(clean_name, con = engine, index = False, if_exists = 'replace', chunksize = 1000, dtype = target_dtypes)
        
        print(f"table '{clean_name}' uploaded successfully with optimized types")
    except Exception as e:
        print(f"table '{clean_name}' failed because: {e}")
print("\nAll processes finished!")

table 'customers' uploaded successfully with optimized types
table 'geolocation' uploaded successfully with optimized types
table 'orders' uploaded successfully with optimized types
table 'order_items' uploaded successfully with optimized types
table 'order_payments' uploaded successfully with optimized types
table 'order_reviews' uploaded successfully with optimized types
table 'products' uploaded successfully with optimized types
table 'sellers' uploaded successfully with optimized types
table 'product_category_name_translation' uploaded successfully with optimized types

All processes finished!